# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565e5c3232e635fdf7262e50c04aa53ae9598704793104fa83550c412814a0912c545b3d2d64d73dae146e1a6347348c1fd7583eabe5074f47ebe6f7cc518b52

test:
  secret_key_base: 09fb01571d01e6df50b8add9c3a982cefd3e426c417de12aa59b62a65290877953ab6635a21340ee9f9d00495a3e7344eaa9856be04cf5268dfc7c0433bdacc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
